{"uuid": "2be07915-21ad-4823-a471-9a8897425030", "children": ["f5271080-a376-465a-9ec7-c293615bc44c"], "befores": [{"name": "environment_setup", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home\n\n", "trace": "  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 949, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/fixtures.py\", line 775, in call_fixture_func\n    res = next(it)\n  File \"/Users/karimovrustam/PycharmProjects/01.23.2020_SeleniumAutomation/Pytest/test_multiSwitchWindow.py\", line 13, in environment_setup\n    driver = Chrome(executable_path=path)\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py\", line 73, in __init__\n    self.service.start()\n  File \"/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/selenium/webdriver/common/service.py\", line 81, in start\n    raise WebDriverException(\n"}, "start": 1581107240138, "stop": 1581107240145}], "start": 1581107240138, "stop": 1581107240272}